name: learn-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  example-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Get Test Secret
        env:
          test_secret: ${{ secrets.TEST_SECRET }}
        run: |
          echo we should never show secrets like this ${{ secret.TEST_SECRET }}
